modified:   .github/workflows/Update RewriteFiles.yml

diff --git a/.github/workflows/Update RewriteFiles.yml b/.github/workflows/Update RewriteFiles.yml
--- a/.github/workflows/Update RewriteFiles.yml
+++ b/.github/workflows/Update RewriteFiles.yml
@@ -19,9 +19,14 @@ jobs:
         LINK="https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt"
         curl -o "Rewrite/Chongxie.conf" "$LINK" || true
         grep -Eo 'https?://[^ ]+\.js' Rewrite/Chongxie.conf > js_links.txt
+        > Rewrite/JavaScript/invalid_links.list
         while IFS= read -r url; do
           filename=$(basename "$url")
-          curl -f -o "Rewrite/JavaScript/$filename" "$url" || true
+          if curl -f --head "$url" 2>/dev/null | grep -q "200 OK"; then
+            curl -f -o "Rewrite/JavaScript/$filename" "$url" || true
+          else
+            echo "$url" >> Rewrite/JavaScript/invalid_links.list
+          fi
         done < js_links.txt
     - name: Commit & copy RewriteFiles
       uses: EndBug/add-and-commit@v9
